// Auto-generated. Do not edit.
#pragma once
#include <stdint.h>

typedef enum {
  MENU_ROOT,
  MENU_PORTAL,
  MENU_START_CLAIM,
  MENU_CONNECTIONS,
  MENU_BAMBU_ENABLED,
  MENU_MOON_ENABLED,
  MENU_HA_ENABLED,
  MENU_MATERIALS,
  MENU_IHEATER_LINK_PLA_TEMP,
  MENU_IHEATER_LINK_PETG_TEMP,
  MENU_IHEATER_LINK_ABS_TEMP,
  MENU_IHEATER_LINK_ASA_TEMP,
  MENU_IHEATER_LINK_PC_TEMP,
  MENU_IHEATER_LINK_PA_TEMP,
  MENU_UNITS_COUNT,
  MENU_LANGUAGE,
  MENU__COUNT
} MenuId;

typedef enum {
  LANG_RU = 0,
  LANG_EN = 1,
  LANG_COUNT
} LangId;
